# Generated by Django 3.2.3 on 2021-06-02 01:45

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('marking', models.CharField(help_text='Model or the main feature of the product.', max_length=40)),
                ('image', models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2)),
                ('unit_for_weight_vol', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('C', 'Child')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('marking', models.CharField(help_text='Model or the main feature of the product.', max_length=40)),
                ('image', models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2)),
                ('unit_for_weight_vol', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foodstuff',
            },
        ),
        migrations.CreateModel(
            name='SmartphoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('marking', models.CharField(help_text='Model or the main feature of the product.', max_length=40)),
                ('image', models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2)),
                ('unit_for_weight_vol', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('ram', models.CharField(max_length=10)),
                ('memory', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Smartphone',
            },
        ),
        migrations.CreateModel(
            name='TvProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('marking', models.CharField(help_text='Model or the main feature of the product.', max_length=40)),
                ('image', models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2)),
                ('unit_for_weight_vol', models.CharField(choices=[('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('screen_diagonal', models.CharField(max_length=10)),
                ('screen_resolution', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'TV',
            },
        ),
        migrations.RemoveField(
            model_name='bproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
        migrations.AddField(
            model_name='specification',
            name='tag',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Name of category'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='addition',
            field=models.CharField(blank=True, max_length=100, verbose_name='additional information'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='available_qty',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='available quantity'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=3),
        ),
        migrations.AlterField(
            model_name='specification',
            name='package_qty',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='package quantity'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight_vol',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight / vol.'),
        ),
        migrations.DeleteModel(
            name='AProduct',
        ),
        migrations.DeleteModel(
            name='BProduct',
        ),
        migrations.DeleteModel(
            name='CProduct',
        ),
        migrations.AddField(
            model_name='tvproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AddField(
            model_name='smartphoneproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
