# Generated by Django 3.2.3 on 2021-06-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210602_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingproduct',
            options={'verbose_name': 'Clothing', 'verbose_name_plural': 'Clothing'},
        ),
    ]
