# Generated by Django 3.2.3 on 2021-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210602_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.'),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg.'), ('LB', 'lb.'))), ('Volume', (('L', 'L.'), ('GL', 'gal.'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('LT', 'lot')], max_length=2, verbose_name='unit for weight / vol.'),
        ),
    ]
