# Generated by Django 3.2.3 on 2021-06-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210602_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categories', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category'),
        ),
    ]
