# Generated by Django 3.2.3 on 2021-06-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210602_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='name'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to=None,
        ),
    ]
