# Generated by Django 3.2.3 on 2021-06-04 01:58

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210604_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path),
        ),
        migrations.AlterField(
            model_name='specification',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to=shop.models.file_directory_path),
        ),
    ]
