# Generated by Django 3.2.3 on 2021-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210604_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingproduct',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2X', 'XXL')], max_length=2),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='memory',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='ram',
            field=models.CharField(max_length=30),
        ),
    ]
