# Generated by Django 3.2.3 on 2021-06-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210604_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='available_qty',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='available quantity'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='package_qty',
            field=models.DecimalField(decimal_places=3, default='1', max_digits=6, verbose_name='package quantity'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight_vol',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='weight / vol.'),
        ),
    ]
