# Generated by Django 3.2.3 on 2021-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210604_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='image',
            field=models.ImageField(blank=True, help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', upload_to='shop/'),
        ),
    ]
