# Generated by Django 3.2.3 on 2021-06-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_specification_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='content_id',
            new_name='object_id',
        ),
    ]
