# Generated by Django 3.2.3 on 2021-06-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210604_2052'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='specification',
            order_with_respect_to=None,
        ),
    ]
