# Generated by Django 3.2.3 on 2021-06-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_specification_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], max_length=1),
        ),
    ]
