# Generated by Django 3.2.3 on 2021-06-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_clothingproduct_gender'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='clothingproduct',
            order_with_respect_to='category',
        ),
        migrations.AlterOrderWithRespectTo(
            name='foodproduct',
            order_with_respect_to='category',
        ),
        migrations.AlterOrderWithRespectTo(
            name='smartphoneproduct',
            order_with_respect_to='category',
        ),
        migrations.AlterOrderWithRespectTo(
            name='tvproduct',
            order_with_respect_to='category',
        ),
    ]
