# Generated by Django 3.2.3 on 2021-06-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20210604_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'item', 'verbose_name_plural': 'cart'},
        ),
    ]
