# Generated by Django 3.2.3 on 2021-06-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0025_category_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'shop'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.category'),
        ),
    ]
