# Generated by Django 3.2.3 on 2021-06-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210611_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category', 'name'], 'verbose_name_plural': 'categories'},
        ),
    ]
