# Generated by Django 3.2.3 on 2021-06-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
