# Generated by Django 3.2.3 on 2021-06-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0028_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'shop', 'model__endswith': 'product'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
