# Generated by Django 3.2.3 on 2021-06-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_category_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingproduct',
            options={'ordering': ['category', 'name'], 'verbose_name': 'clothing', 'verbose_name_plural': 'clothing'},
        ),
        migrations.AlterModelOptions(
            name='foodproduct',
            options={'ordering': ['category', 'name'], 'verbose_name': 'foodstuff'},
        ),
        migrations.AlterModelOptions(
            name='smartphoneproduct',
            options={'ordering': ['category', 'name'], 'verbose_name': 'smartphone'},
        ),
        migrations.AlterModelOptions(
            name='tvproduct',
            options={'ordering': ['category', 'name'], 'verbose_name': 'TV'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='clothingproduct',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='foodproduct',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='smartphoneproduct',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='tvproduct',
            order_with_respect_to=None,
        ),
    ]
