# Generated by Django 3.2.3 on 2021-06-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20210615_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingproduct',
            options={'ordering': ['-date_added'], 'verbose_name': 'clothing', 'verbose_name_plural': 'clothing'},
        ),
        migrations.AlterModelOptions(
            name='foodproduct',
            options={'ordering': ['-date_added'], 'verbose_name': 'foodstuff'},
        ),
        migrations.AlterModelOptions(
            name='smartphoneproduct',
            options={'ordering': ['-date_added'], 'verbose_name': 'smartphone'},
        ),
        migrations.AlterModelOptions(
            name='tvproduct',
            options={'ordering': ['-date_added'], 'verbose_name': 'TV'},
        ),
    ]
