# Generated by Django 3.2.3 on 2021-06-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20210615_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0', help_text='The rate from 0.00 to 0.99 for example a 20% discount is 0.20', max_digits=2),
        ),
    ]
