# Generated by Django 3.2.3 on 2021-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_specification_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='package_qty',
        ),
        migrations.AddField(
            model_name='specification',
            name='pre_packing',
            field=models.DecimalField(decimal_places=3, default='1', max_digits=6, verbose_name='pre-packing'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='KG', max_length=2, verbose_name='unit for weight/volume'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='KG', max_length=2, verbose_name='unit for weight/volume'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='KG', max_length=2, verbose_name='unit for weight/volume'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight_vol',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='weight/volume'),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kg'), ('LB', 'lb'))), ('Volume', (('L', 'L'), ('GL', 'gal'))), ('PC', 'piece'), ('PK', 'pack'), ('PR', 'pair'), ('BL', 'bottle'), ('LT', 'lot')], default='KG', max_length=2, verbose_name='unit for weight/volume'),
        ),
    ]
