# Generated by Django 3.2.3 on 2021-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_specification_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specification',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default='0', help_text='Special price which replaces the discounted price', max_digits=9),
        ),
    ]
