# Generated by Django 3.2.3 on 2021-06-28 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20210620_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specification',
            name='discount',
            field=models.PositiveIntegerField(default='0', help_text='Discounts from 1 to 99%.'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default='0', editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='specification',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default='0', help_text='Special price replaces the discount price, "0" is disabled', max_digits=9),
        ),
    ]
