# Generated by Django 3.2.3 on 2021-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20210628_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='discount',
            field=models.PositiveIntegerField(default='0', help_text='A discount from 0 to 99%.'),
        ),
    ]
