# Generated by Django 3.2.3 on 2021-06-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_specification_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='discount',
        ),
    ]
