# Generated by Django 3.2.3 on 2021-06-28 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_specification_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='discount',
            field=models.IntegerField(default='0', help_text='A discount from 0 to 99%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
